export interface TblusuarioModel {
  ID: string,
  USERNAME: string,
  CLAVE: string,
  ESTADO: string,
  FECHAINICIAL: string,
  FECHAFINAL: string,
  HORAINICIAL: string,
  HORAFINAL: string,
  IDCOBRADOR: string,
  NOMBRES: string,
  APELLIDOS: string,
  MAQUINA: string,
  NIT: string,
  PREFIJO: string,
  IDCAJAIND: string,
  IDCAJAEMP: string,
  IDCAJAPAR: string,
  IDCAJA: string,
  IDCAJAANT: string,
}
